const fs = require('fs');
const path = require('path');
const postcss = require('postcss');
const tailwindcss = require('@tailwindcss/postcss');

async function build() {
  const inputCssPath = path.join(__dirname, '../src/index.css');
  const outputTsPath = path.join(__dirname, '../src/generated-styles.ts');
  const css = fs.readFileSync(inputCssPath, 'utf8');

  const result = await postcss([
    tailwindcss()
  ]).process(css, { from: inputCssPath, to: outputTsPath });

  const cleanedCss = result.css;
  const content = `// Auto-generated by scripts/build-styles.js - DO NOT EDIT MANUALLY\nexport const PACKAGE_STYLES = ${JSON.stringify(cleanedCss)};\n`;

  fs.writeFileSync(outputTsPath, content, 'utf8');
  console.log('Successfully generated src/generated-styles.ts');
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
