const fs = require('fs');
const path = require('path');
const postcss = require('postcss');
const tailwindcss = require('@tailwindcss/postcss');

async function build() {
  const inputCssPath = path.join(__dirname, '../src/index.css');
  const outputTsPath = path.join(__dirname, '../src/generated-styles.ts');
  const css = fs.readFileSync(inputCssPath, 'utf8');

  const result = await postcss([
    tailwindcss()
  ]).process(css, { from: inputCssPath, to: outputTsPath });

  let cleanedCss = result.css;

  // 1. Remove global layer order re-declarations that override host app responsive media queries
  cleanedCss = cleanedCss.replace(/@layer\s+theme,\s*base,\s*components,\s*utilities;/g, '');
  cleanedCss = cleanedCss.replace(/@layer\s+properties;/g, '');

  // 2. Scope @layer base rules so global element resets (button, input, *, etc.) apply ONLY inside .media-uploader-scope
  cleanedCss = cleanedCss.replace(
    /@layer base\s*\{([\s\S]*?)\n\}/g,
    (match, baseContent) => {
      const scopedContent = baseContent.replace(
        /([^\},\{]+)\{/g,
        (selectorMatch, selectors) => {
          if (
            selectors.includes('@') ||
            selectors.includes(':root') ||
            selectors.includes(':host')
          ) {
            return selectorMatch;
          }
          const scopedSelectors = selectors
            .split(',')
            .map((s) => {
              const trimmed = s.trim();
              if (!trimmed) return trimmed;
              if (trimmed.startsWith('.media-uploader-scope')) return trimmed;
              return `.media-uploader-scope ${trimmed}`;
            })
            .join(', ');
          return `${scopedSelectors} {`;
        }
      );
      return `@layer base {\n${scopedContent}\n}`;
    }
  );

  // 3. Wrap entire package CSS in an isolated cascade layer so host app media queries & utilities always take precedence
  cleanedCss = `@layer media-uploader-layer {\n${cleanedCss}\n}`;

  const content = `// Auto-generated by scripts/build-styles.js - DO NOT EDIT MANUALLY\nexport const PACKAGE_STYLES = ${JSON.stringify(cleanedCss)};\n`;

  fs.writeFileSync(outputTsPath, content, 'utf8');
  console.log('Successfully generated src/generated-styles.ts with @layer media-uploader-layer isolation');
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
